# Generated by Django 6.0 on 2026-01-02 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of exam in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_time', models.DateTimeField(db_index=True, help_text='When the exam becomes available')),
                ('end_time', models.DateTimeField(db_index=True, help_text='When the exam closes')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum score to pass (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of submission attempts allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like instructions, resources, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('ESSAY', 'Essay'), ('TF', 'True/False')], db_index=True, max_length=10)),
                ('question_text', models.TextField(help_text='The question text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the exam')),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, help_text='Marks allocated to this question', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_answer', models.JSONField(help_text='Expected answer(s) - structure depends on question type')),
                ('options', models.JSONField(blank=True, help_text='Options for multiple choice questions', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like hints, explanation, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADING', 'Grading'), ('GRADED', 'Graded')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score as percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total marks obtained', max_digits=6, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total marks for the exam', max_digits=6, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='Grading feedback and comments')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.JSONField(help_text="Student's answer - structure depends on question type")),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.submission')),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['submission', 'question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code', 'instructor'], name='courses_code_ead667_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'start_time', 'end_time'], name='exams_status_42658f_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'status'], name='exams_course__149a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='questions_exam_id_6a4fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', '-submitted_at'], name='submissions_student_02388e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['exam', 'student', 'attempt_number'], name='submissions_exam_id_077289_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'submitted_at'], name='submissions_status_ac0821_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'exam', '-attempt_number'], name='submissions_student_b3d84a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('exam', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'question'], name='answers_submiss_4fd023_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct'], name='answers_questio_e218ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
